import React,{useEffect,useState}from"react";import katex from"katex";import"katex/dist/katex.min.css";import{CheckCircle2,Circle,Menu,Moon,Sun,X}from"lucide-react";
const T=[
["判別式と解の構造","解の個数・重解・2解の差",String.raw`(\alpha-\beta)^2=\frac{D}{a^2}`,"2解を直接求めず、差や一致条件を判別式へ翻訳する。",String.raw`x^2-(m+2)x+2m=0`,"2解の差の絶対値が3となるmを求めよ。",[String.raw`D=(m-2)^2`,String.raw`(\alpha-\beta)^2=D=9`,String.raw`m=-1,\ 5`]],
["解の配置","区間・半直線に入る条件",String.raw`D,\ \text{軸},\ f(k)`,"実数解、軸の位置、境界での符号を同時に確認する。",String.raw`x^2-2mx+m+2=0`,"2解がともに1より大きくなるmの範囲を求めよ。",[String.raw`D=4(m-2)(m+1)>0`,String.raw`m>1,\quad f(1)=3-m>0`,String.raw`2<m<3`]],
["解と係数の関係","対称式・整数解・新しい方程式",String.raw`\alpha+\beta=-\frac ba,\quad\alpha\beta=\frac ca`,"解を文字のまま扱い、対称式を和と積に変形する。",String.raw`x^2-3x+1=0`,"2解をα、βとするとき、α⁴+β⁴を求めよ。",[String.raw`\alpha+\beta=3,\ \alpha\beta=1`,String.raw`\alpha^2+\beta^2=7`,String.raw`\alpha^4+\beta^4=49-2=47`]],
["放物線と直線","共有点・接線・弦の中点",String.raw`f(x)=g(x)`,"交点を個別に求めず、解の和と積で中点や距離を処理する。",String.raw`y=x^2,\quad y=2tx-t^2+1`,"2交点A、Bの中点Mの軌跡を求めよ。",[String.raw`x^2-2tx+t^2-1=0`,String.raw`X_M=t,\quad Y_M=t^2+1`,String.raw`Y=X^2+1`]],
["軸が動く最大・最小","固定区間と場合分け",String.raw`f(x)=(x-a)^2+c`,"軸が定義域の左・内部・右にある場合を先に分ける。",String.raw`f(x)=x^2-2ax+2a,\quad0\le x\le3`,"最小値をaの式で表せ。",[String.raw`f(x)=(x-a)^2-a^2+2a`,String.raw`a<0:\ 0`,String.raw`0\le a\le3:\ -a^2+2a`,String.raw`a>3:\ 9-4a`]],
["定義域が動く最大・最小","区間と頂点の位置関係",String.raw`a\le x\le a+2`,"頂点が区間内かに加え、どちらの端点が軸から遠いかを見る。",String.raw`f(x)=x^2-4x+5`,"a≦x≦a+2における最大値を求めよ。",[String.raw`f(x)=(x-2)^2+1`,String.raw`f(a)-f(a+2)=4(1-a)`,String.raw`a\le1:\ f(a),\quad a\ge1:\ f(a+2)`]],
["2次不等式と定数","恒成立・解集合の包含",String.raw`ax^2+bx+c\ge0\ (\forall x)`,"最高次係数が0になる退化ケースを最初に分ける。",String.raw`(m-1)x^2-2mx+m+3\ge0`,"すべての実数xで成り立つmを求めよ。",[String.raw`m=1:\ \text{恒成立しない}`,String.raw`m>1,\quad D\le0`,String.raw`m\ge3`]],
["絶対値と実数解の個数","グラフの折り返し",String.raw`|f(x)|=k`,"元の放物線の負の部分をx軸対称に折り返し、水平線との交点を数える。",String.raw`|x^2-4x+3|=k`,"実数解の個数をkで分類せよ。",[String.raw`x^2-4x+3=(x-2)^2-1`,String.raw`k<0:0,\ k=0:2`,String.raw`0<k<1:4,\ k=1:3,\ k>1:2`]],
["2次方程式への帰着","置換・高次式・無理方程式",String.raw`t=g(x)`,"繰り返し現れるまとまりを置換し、最後に元の変数へ戻す。",String.raw`(x^2-2x)^2-5(x^2-2x)+4=0`,"方程式を解け。",[String.raw`t=x^2-2x`,String.raw`t^2-5t+4=0\Rightarrow t=1,4`,String.raw`x=1\pm\sqrt2,\ 1\pm\sqrt5`]],
["存在条件・通過領域","パラメータについての方程式",String.raw`F(x,y,a)=0`,"点(x,y)を固定し、実数パラメータが存在する条件D≧0を使う。",String.raw`y=x^2-2ax+a^2+a`,"実数aを動かすときの通過領域を求めよ。",[String.raw`a^2+(1-2x)a+x^2-y=0`,String.raw`D_a=(1-2x)^2-4(x^2-y)\ge0`,String.raw`y\ge x-\frac14`]],
["条件付き最適化","2変数を1変数へ",String.raw`x+y=s\Rightarrow y=s-x`,"制約式で1変数を消去し、定義域付き2次関数へ帰着する。",String.raw`x+y=6,\quad x,y\ge0`,"x²+2y²の最小値を求めよ。",[String.raw`x^2+2(6-x)^2=3(x-4)^2+24`,String.raw`0\le x\le6`,String.raw`\min=24\quad(x,y)=(4,2)`]],
["融合・実用問題","運動・利益・図形の最適化",String.raw`y=ax^2+bx+c`,"定義域、単位、現実的条件を含めて結論を書く。",String.raw`h(t)=-5t^2+20t+1`,"最大高度とその時刻を求めよ。",[String.raw`h(t)=-5(t-2)^2+21`,String.raw`t=2\ge0`,String.raw`2\text{秒後に最大高度 }21\text{m}`]]
];
function F({x,inline=false}){let h=katex.renderToString(x,{throwOnError:false,displayMode:!inline});return inline?<span className="f in" dangerouslySetInnerHTML={{__html:h}}/>:<div className="f" dangerouslySetInnerHTML={{__html:h}}/>}
export default function App(){const[dark,setDark]=useState(false),[menu,setMenu]=useState(false),[open,setOpen]=useState({}),[done,setDone]=useState(()=>JSON.parse(localStorage.getItem("univ-progress")||"{}"));useEffect(()=>localStorage.setItem("univ-progress",JSON.stringify(done)),[done]);let nav=<aside><div className="brand"><b>数学学習ノート</b><small>大学入試対策</small><button onClick={()=>setMenu(false)}><X/></button></div>{T.map((t,i)=><a key={i} href={`#u${i+1}`} onClick={()=>setMenu(false)}><span>{String(i+1).padStart(2,"0")}</span>{t[0]}</a>)}</aside>;return <div className={dark?"app dark":"app"}>{menu&&<div className="shade" onClick={()=>setMenu(false)}/>}<div className={menu?"mobile show":"mobile"}>{nav}</div><div className="desk">{nav}</div><div className="content"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><small>高校数学I・大学入試対策</small><h1>2次方程式・2次関数 大学入試問題集</h1></div><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header><main><section className="hero"><div><span>標準から発展へ</span><h2>条件を数式へ翻訳し<br/>解法を設計する</h2><p>公式暗記ではなく、着眼点、最初の一手、論理的な答案作成を学ぶ。</p></div><ol><li>条件を図・式へ翻訳</li><li>必要条件を整理</li><li>場合分けの境界を決定</li><li>結論と条件を再確認</li></ol></section>{T.map((t,i)=><section className="unit" id={`u${i+1}`} key={i}><div className="head"><span>{String(i+1).padStart(2,"0")}</span><div><em>{i<3?"標準・応用":i<9?"応用":"発展"}</em><h2>{t[0]}</h2><p>{t[1]}</p></div><button onClick={()=>setDone(d=>({...d,[i]:!d[i]}))}>{done[i]?<CheckCircle2/>:<Circle/>}{done[i]?"習得済み":"習得済みにする"}</button></div><div className="core"><b>核心</b><p>{t[3]}</p><F x={t[2]}/></div><article><div className="tag">標準例題</div><h3><F x={t[4]} inline/>{t[5]}</h3><button onClick={()=>setOpen(o=>({...o,[i]:!o[i]}))}>{open[i]?"答案を閉じる":"着眼点・模範答案"}</button>{open[i]&&<div className="sol"><b>解法のプロセス</b>{t[6].map((x,j)=><F x={x} key={j}/>)}<div className="note">計算結果だけでなく、使用した条件と場合分けの根拠も答案に残す。</div></div>}</article><div className="practice"><b>対応演習の方向</b><p>{t[1]}を、定数・区間・絶対値・グラフ条件を変えて再現する。</p></div></section>)}</main></div></div>}
