import React,{useEffect,useRef,useState}from"react";import katex from"katex";import"katex/dist/katex.min.css";import{BookOpen,CheckCircle2,Circle,Menu,Moon,Pause,Play,RotateCcw,Sun,X}from"lucide-react";
function Formula({tex,inline=false}){const html=katex.renderToString(tex,{throwOnError:false,displayMode:!inline});return inline?<span className="formula inline" dangerouslySetInnerHTML={{__html:html}}/>:<div className="formula" dangerouslySetInnerHTML={{__html:html}}/>}
const chapters=["異符号の2解をグラフで理解","解の配置とパラメータ","放物線と直線の共有点","最大・最小と場合分け","2次不等式の恒成立"];
const qs=[
{lv:"標準",q:String.raw`x^2-(m+1)x-m=0`,text:" が異符号の2解をもつような m の範囲を求めよ。",hint:"2解の積が負であることを使う。",steps:[String.raw`\alpha\beta=-m`,String.raw`\alpha\beta<0\iff -m<0`,String.raw`m>0`],ans:String.raw`m>0`},
{lv:"応用",q:String.raw`x^2-2mx+m+2=0`,text:" の2解がともに1より大きくなるような m の範囲を求めよ。",hint:"D>0、軸>1、f(1)>0 の3条件。",steps:[String.raw`D=4(m-2)(m+1)>0`,String.raw`m>1`,String.raw`f(1)=3-m>0`],ans:String.raw`2<m<3`},
{lv:"応用",q:String.raw`y=x^2`,text:" と直線 y=2tx-t²+1 の2交点の中点の軌跡を求めよ。",hint:"交点のx座標をα、βとして和と積を使う。",steps:[String.raw`x^2-2tx+t^2-1=0`,String.raw`X=\frac{\alpha+\beta}{2}=t`,String.raw`Y=\frac{\alpha^2+\beta^2}{2}=t^2+1`],ans:String.raw`Y=X^2+1`},
{lv:"発展",q:String.raw`f(x)=x^2-2ax+2a,\quad0\le x\le3`,text:" の最小値を a の式で表せ。",hint:"軸x=aが区間の左・内部・右にある場合。",steps:[String.raw`f(x)=(x-a)^2-a^2+2a`,String.raw`a<0:\ 0`,String.raw`0\le a\le3:\ -a^2+2a`,String.raw`a>3:\ 9-4a`],ans:String.raw`\min f=\begin{cases}0&(a<0)\\-a^2+2a&(0\le a\le3)\\9-4a&(a>3)\end{cases}`},
{lv:"発展",q:String.raw`(m-1)x^2-2mx+m+3\ge0`,text:" がすべての実数xで成り立つmを求めよ。",hint:"m=1の退化ケースを先に分ける。",steps:[String.raw`m=1:\ -2x+4\ge0\text{ は恒成立しない}`,String.raw`m>1,\quad D\le0`,String.raw`D=4m^2-4(m-1)(m+3)\le0`],ans:String.raw`m\ge3`}
];
function Graph(){const ref=useRef(null);const[a,setA]=useState(1),[b,setB]=useState(0),[c,setC]=useState(-4),[playing,setPlaying]=useState(false);useEffect(()=>{if(!playing)return;let d=1,id=setInterval(()=>setC(v=>{let n=v+d*.12;if(n>1||n<-5)d*=-1;return n}),45);return()=>clearInterval(id)},[playing]);useEffect(()=>{const cvs=ref.current,ctx=cvs.getContext("2d"),w=cvs.width=cvs.clientWidth*devicePixelRatio,h=cvs.height=cvs.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=cvs.clientWidth,H=cvs.clientHeight,s=42,ox=W/2,oy=H/2;ctx.clearRect(0,0,W,H);ctx.fillStyle="#081120";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#1d2a3d";ctx.lineWidth=1;for(let x=ox%s;x<W;x+=s){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy%s;y<H;y+=s){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle="#91a4be";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,oy);ctx.lineTo(W,oy);ctx.moveTo(ox,0);ctx.lineTo(ox,H);ctx.stroke();ctx.strokeStyle="#60a5fa";ctx.lineWidth=3;ctx.beginPath();let first=true;for(let px=0;px<W;px++){let x=(px-ox)/s,y=a*x*x+b*x+c,py=oy-y*s;if(py>-200&&py<H+200){if(first){ctx.moveTo(px,py);first=false}else ctx.lineTo(px,py)}}ctx.stroke();let D=b*b-4*a*c;if(D>=0&&a!==0){let roots=[(-b-Math.sqrt(D))/(2*a),(-b+Math.sqrt(D))/(2*a)];roots.forEach((x,i)=>{let px=ox+x*s;ctx.fillStyle=i===0?"#f59e0b":"#34d399";ctx.beginPath();ctx.arc(px,oy,7,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="13px sans-serif";ctx.fillText(`x${i+1}=${x.toFixed(2)}`,px-28,oy+24)});ctx.fillStyle="#fff";ctx.font="bold 14px sans-serif";ctx.fillText(roots[0]<0&&roots[1]>0?"x₁ < 0 < x₂  →  異符号":"異符号ではありません",14,24)}},[a,b,c]);let D=b*b-4*a*c,prod=a?c/a:NaN;return <div className="visual"><div className="canvasHead"><div><span>動くグラフ</span><h3>2つの解が異符号になる意味</h3></div><button onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?"停止":"再生"}</button></div><canvas ref={ref}/><div className="controls"><label>a <input type="range" min="-2" max="2" step="0.1" value={a} onChange={e=>setA(+e.target.value)}/><b>{a.toFixed(1)}</b></label><label>b <input type="range" min="-5" max="5" step="0.1" value={b} onChange={e=>setB(+e.target.value)}/><b>{b.toFixed(1)}</b></label><label>c <input type="range" min="-5" max="3" step="0.1" value={c} onChange={e=>setC(+e.target.value)}/><b>{c.toFixed(1)}</b></label></div><div className="status"><div><small>判別式</small><Formula tex={String.raw`D=${D.toFixed(2)}`}/></div><div><small>2解の積</small><Formula tex={String.raw`\alpha\beta=\frac ca=${isFinite(prod)?prod.toFixed(2):"-"}`}/></div><div className={D>0&&prod<0?"ok":"ng"}><small>判定</small><b>{D>0&&prod<0?"異なる2つの実数解・異符号":"条件を満たさない"}</b></div></div><p className="explain">2つの交点が原点をはさんで左右に分かれると、左の解は負、右の解は正です。したがって積は負になります。逆に、2実数解があり積が負なら、2解は必ず異符号です。</p></div>}
function Exercise({x,i}){const[hint,setHint]=useState(false),[ans,setAns]=useState(false);return <article><div className="qtop"><span>{x.lv}</span><b>問題 {i+1}</b></div><h3><Formula tex={x.q} inline/>{x.text}</h3><div className="buttons"><button onClick={()=>setHint(!hint)}>着眼点</button><button className="primary" onClick={()=>setAns(!ans)}>模範答案</button></div>{hint&&<div className="hint">{x.hint}</div>}{ans&&<div className="answer"><ol>{x.steps.map((s,j)=><li key={j}><Formula tex={s}/></li>)}</ol><div className="final"><b>答</b><Formula tex={x.ans}/></div></div>}</article>}
export default function App(){const[dark,setDark]=useState(false),[menu,setMenu]=useState(false),[done,setDone]=useState({});const nav=<aside><div className="brand"><b>数学学習ノート</b><small>大学入試対策</small><button onClick={()=>setMenu(false)}><X/></button></div><a href="#visual">グラフで理解</a>{chapters.map((x,i)=><a href={`#c${i}`} key={x}>{String(i+1).padStart(2,"0")} {x}</a>)}</aside>;return <div className={dark?"app dark":"app"}>{menu&&<div className="shade" onClick={()=>setMenu(false)}/>}<div className={menu?"mobile show":"mobile"}>{nav}</div><div className="desk">{nav}</div><div className="content"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><small>高校数学I・大学入試対策</small><h1>2次方程式・2次関数 実戦問題集</h1></div><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header><main><section className="hero"><div><span>INTERACTIVE WORKBOOK</span><h2>グラフを動かして<br/>条件の意味を理解する</h2><p>着眼点、解法設計、模範答案、動くグラフを1つの流れで学習。</p></div><div className="heroStats"><div><b>5</b><span>重点テーマ</span></div><div><b>5</b><span>実戦問題</span></div><div><b>1</b><span>動的教材</span></div></div></section><section id="visual"><Graph/></section>{qs.map((q,i)=><section className="chapter" id={`c${i}`} key={i}><div className="chapterHead"><div><span>{String(i+1).padStart(2,"0")}</span><h2>{chapters[i]}</h2></div><button onClick={()=>setDone(d=>({...d,[i]:!d[i]}))}>{done[i]?<CheckCircle2/>:<Circle/>}{done[i]?"完了":"学習済みにする"}</button></div><Exercise x={q} i={i}/></section>)}</main></div></div>}
